kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.storage }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
